name: TEST PR workflow
on:
  pull_request:

jobs:
  predict-pr-noapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./

      - name: Run predict on test files
        id: prediction
        uses: ./
        with:
          log_level: "debug"
          path: ./test

      - name: Output prediction
        run: |
          echo "${{ steps.prediction.outputs.PREDICTION_TABLE }}"

      - name: Update PR with prediction results
        uses: edumserrano/find-create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '<!-- kubecost-prediction-results -->'
          comment-author: 'github-actions[bot]'
          edit-mode: replace
          body: |
            <!-- kubecost-prediction-results -->

            ## Kubecost's cost prediction

            ```
            ${{ steps.prediction.outputs.PREDICTION_TABLE }}
            ```
